#!/bin/bash
# elaborado por sinfallas
if [ $USER != root ]; then
echo -e "\e[00;31mERROR DEBES SER ROOT\e[00m"
exit 0
echo "deb http://packages.prosody.im/debian stable main" | tee -a /etc/apt/sources.list
wget http://prosody.im/files/prosody-debian-packages.key -O- | apt-key add -
apt-get update
apt-get -y install sasl2-bin libsasl2-modules-ldap prosody liblua5.1-{sec0,cyrussasl0,event-prosody0}
cd /etc/prosody/certs
openssl req -new -x509 -days 1095 -nodes -out "midominio.cu.cert" -keyout "midominio.cu.key"



iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -i eth1 -s 192.168.0.0/24 -p tcp -m tcp -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i eth1 -s 192.168.0.0/24 -p tcp -m tcp -m multiport --dports 5222,5223,5269 -m state --state NEW -j ACCEPT



