#!/bin/bash
TARGET="8.8.8.8"
LOG="/var/log/enlace.log"
PING=$(ping -n -c 3 -i 2 -W 3 $TARGET 2>&1)
if [[ $? != 0 ]]
then
    	if [[ $PING =~ "loss" ]]
        then
            	ERROR=$(echo "$PING" | grep 'loss')
        else
            	ERROR=$PING
        fi
	echo "$(date +%F\ %T) - Failed check - $ERROR" &>> $LOG
fi
exit 0
