#!/bin/bash
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -d 0.0.0.0/0  -j MASQUERADE
#service squid3 stop
#rm -rf /var/spool/squid3/*
#squid3 -z
#service squid3 restart
#service isc-dhcp-server restart
#service apache2 restart
echo "Finalizado..."
exit 0
