#!/bin/bash
source variables
echo "$(date +%d/%m/%Y-%r) ========== Inicio del sistema" >> $log
ifconfig eth0 down
tunctl
ifconfig tap0 up
brctl addbr br0
brctl addif br0 eth0
brctl addif br0 tap0
brctl stp br0 off
ifconfig eth0 0.0.0.0 up
ifconfig br0 up
modprobe virtio_balloon
service qemu-kvm start
vde_switch -d -F --macaddr $mac -g $switchg -p $pid/switch1.pid -s $sock1 -M $sock1/switch1.mgmt --mgmtgroup $switchg
vde_switch -d -F --macaddr $mac -g $switchg -p $pid/switch2.pid -s $sock2 -M $sock2/switch2.mgmt --mgmtgroup $switchg
for (( n=1; n<=$vmtotal; n++ ))
do
	ciclo=`echo $!vm$n`
	ciclo2=`echo $!run$n`
	ciclo3=`echo $!vmc$n`
	if [[ ${!ciclo2} = 1 ]]; then
		echo -e "\e[00;31mIniciando ${!ciclo}\e[00m"
		echo "$(date +%d/%m/%Y-%r) Iniciando ${!ciclo}" >> $log
		${!ciclo3}
		$tiempo
	fi
done
