#!/bin/bash
# optimizaciones
if [ $USER != root ]; then
echo "Error: debes ser root"
exit 0
fi
echo -e "vm.swappiness = 10""\n""vm.dirty_background_ratio = 10""\n""vm.dirty_ratio = 25""\n""vm.vfs_cache_pressure = 40""\n""vm.dirty_writeback_centisecs = 1500""\n""vm.mmap_min_addr = 4096""\n""kernel.shmmni = 4096""\n""kernel.shmall = 536870912""\n""kernel.shmmax = 2147483648""\n""kernel.sched_autogroup_enabled = 1""\n""kernel.sched_rt_runtime_us = 950000""\n""kernel.threads-max = 98006""\n""net.ipv6.conf.all.disable_ipv6 = 1""\n""net.ipv6.conf.default.disable_ipv6 = 1""\n""net.ipv6.conf.lo.disable_ipv6 = 1""\n""net.ipv4.tcp_timestamps = 0""\n""net.ipv4.tcp_sack = 1""\n""net.ipv4.tcp_window_scaling = 1""\n""net.core.rmem_max = 16777216""\n""net.core.wmem_max = 16777216""\n""net.ipv4.tcp_rmem = 4096 87380 16777216""\n""net.ipv4.tcp_wmem = 4096 65536 16777216""\n""net.ipv4.tcp_no_metrics_save = 1""\n""net.core.netdev_max_backlog = 2500""\n""fs.file-max = 307615""\n""fs.aio-max-nr = 1048576""\n""net.isr.direct=1" >> /etc/sysctl.conf
poweroff
exit 0
